---
- name: Create WAS group
  group:
    name: "{{ was.group }}"

- name: Create WAS user
  user:
    name: "{{ was.user }}"
    group: "{{ was.group }}"
    shell: "{{ was.default_shell }}"
    
- name: Create installation dir "{{ was.installation_dir }}"
  file:
    state: directory
    path: "{{ was.installation_dir }}"
    mode: 0755
    owner: "{{ was.user }}"
    group: "{{ was.group }}"
    
- name: Cleanup temporary dir "{{ was.tmp_dir }}"
  file:
    state: absent
    path: "{{ was.tmp_dir }}"
    mode: 0755
    owner: "{{ was.user }}"
    group: "{{ was.group }}"
    
- name: Create temporary dir "{{ was.tmp_dir }}"
  file:
    state: directory
    path: "{{ was.tmp_dir }}"
    mode: 0755
    owner: "{{ was.user }}"
    group: "{{ was.group }}"
    
- name: Extract WAS files into "{{ was.tmp_dir }}"
  unarchive:
    src: "was_dummy_archive.tar.gz"
    dest: "{{ was.tmp_dir }}"
    copy: no
- name: Generate WAS response file
  template:
    src: "was_response_file.j2"
    dest: "{{ was.tmp_dir }}/{{ was.response_file_name }}"
...