---
- name: Extract WAS files into "{{ was.tmp_dir }}"
  unarchive:
    src: "{{ lookup('fileglob', './files/{{ was.distrib_name }}.tar.gz') }}"
    dest: "{{ was.tmp_dir }}/"
#    copy: no
    
- name: Generate WAS response file
  template:
    src: "was_response_file.j2"
    dest: "{{ was.tmp_dir }}/{{ was.response_file_name }}"
...