---
- name: Extract files into "{{ was_tmp_dir }}"
  unarchive:
    src: "{{ lookup('fileglob', './files/{{ item }}*.tar.gz') }}"
    dest: "{{ was_tmp_dir }}/"
  loop:
    - "{{ was_distrib_name }}"
    
- name: Generate response file
  template:
    src: "was_response.j2"
    dest: "{{ was_tmp_dir }}/{{ was_response_file_name }}"
...