---
- name: Extract WAS files into "{{ was.tmp_dir }}"
  unarchive:
    src: "was_dummy_archive.tar.gz"
    dest: "{{ was.tmp_dir }}"
    copy: no
- name: Generate WAS response file
  template:
    src: "was_response_file.j2"
    dest: "{{ was.tmp_dir }}/{{ was.response_file_name }}"
...