---
- name: Create WAS group
  group:
    name: "{{ was_group }}"

- name: Create WAS user
  user:
    name: "{{ was_user }}"
    group: "{{ was_group }}"
    shell: "{{ was_default_shell }}"
    
- name: Create instalation dir "{{ was_installation_dir }}"
  file:
    state: directory
    path: "{{ was_installation_dir }}"
    mode: 0755
    owner: "{{ was_user }}"
    group: "{{ was_group }}"
    
- name: Cleanup temporary dir "{{ was_tmp_dir }}"
  file:
    state: absent
    path: "{{ was_tmp_dir }}"
    mode: 0755
    owner: "{{ was_user }}"
    group: "{{ was_group }}"
    
- name: Create temporary dir "{{ was_tmp_dir }}"
  file:
    state: directory
    path: "{{ was_tmp_dir }}"
    mode: 0755
    owner: "{{ was_user }}"
    group: "{{ was_group }}"
    
...