---
- name: Install WAS services
  hosts: was
  become: yes
  become_user: root
  roles:
    - { role: check_vars }
    - { role: check_envoronment, when: "was_vars_ok is defined" }
    - { role: install_was, when: "was_environment_ok is defined" }
...
