---
- name: check was_group
  assert:
    that:
    - was_group is defined and was_group != ''
    msg: "Set the value of 'was_group' in the inventory file."
    
- name: check was_user
  assert:
    that:
    - was_user is defined and was_user != ''
    msg: "Set the value of 'was_user' in the inventory file."
    
- name: check was_installation_dir
  assert:
    that:
    - was_installation_dir is defined and was_installation_dir != ''
    msg: "Set the value of 'was_installation_dir' in the inventory file."
    
- name: check was_tmp_dir
  assert:
    that:
    - was_tmp_dir is defined and was_tmp_dir != ''
    msg: "Set the value of 'was_tmp_dir' in the inventory file."
    
- name: check was_profile_dir
  assert:
    that:
    - was_profile_dir is defined and was_profile_dir != ''
    msg: "Set the value of 'was_profile_dir' in the inventory file."
    
- name: define special variable was_vars_ok
  assert:
    that:
    - was_vars_ok is not defined
    registry: was_vars_ok
...
