---
- name: check was.group
  assert:
    that:
    - was.group is defined and was.group != ''
    msg: "Set the value of 'was.group' in the inventory file."
    
- name: check was.user
  assert:
    that:
    - was.user is defined and was.user != ''
    msg: "Set the value of 'was.user' in the inventory file."
    
- name: check was.installation_dir
  assert:
    that:
    - was.installation_dir is defined and was.installation_dir != ''
    msg: "Set the value of 'was.installation_dir' in the inventory file."
    
- name: check was.tmp_dir
  assert:
    that:
    - was.tmp_dir is defined and was.tmp_dir != ''
    msg: "Set the value of 'was.tmp_dir' in the inventory file."
    
- name: check was.profile_dir
  assert:
    that:
    - was.profile_dir is defined and was.profile_dir != ''
    msg: "Set the value of 'was.profile_dir' in the inventory file."
...
