---
- name: check was_user_os
  assert:
    that:
    - was_user_os is defined and was_user_os != ''
    msg: "Set the value of 'was_user_os' in the inventory file."
    
- name: check was_group_os
  assert:
    that:
    - was_group_os is defined and was_group_os != ''
    msg: "Set the value of 'was_group_os' in the inventory file."
    
- name: check was_root_path
  assert:
    that:
    - was_root_path is defined and was_root_path != ''
    msg: "Set the value of 'was_root_path' in the inventory file."
    
- name: check was_user_dmgr
  assert:
    that:
    - was_user_dmgr is defined and was_user_dmgr != ''
    msg: "Set the value of 'was_user_dmgr' in the inventory file."
    
- name: check was_password_dmgr
  assert:
    that:
    - was_password_dmgr is defined and was_password_dmgr != ''
    msg: "Set the value of 'was_password_dmgr' in the inventory file."
    
- name: check was_cell_name_dmgr
  assert:
    that:
    - was_cell_name_dmgr is defined and was_cell_name_dmgr != ''
    msg: "Set the value of 'was_cell_name_dmgr' in the inventory file."
    
- name: check was_node_name_dmgr
  assert:
    that:
    - was_node_name_dmgr is defined and was_node_name_dmgr != ''
    msg: "Set the value of 'was_node_name_dmgr' in the inventory file."
    
- name: check was_installation_dir
  assert:
    that:
    - was_installation_dir is defined and was_installation_dir != ''
    msg: "Set the value of 'was_installation_dir' in the inventory file."
    
- name: check was_template_path
  assert:
    that:
    - was_template_path is defined and was_template_path != ''
    msg: "Set the value of 'was_template_path' in the inventory file."
    
- name: Variables is OK
  debug:
    msg: "All variables checked sacessfully."
  register: was_vars_ok
...
