galaxy_info:
  author: Andrey Shokhin
  description: Install IBM WebSphere on AIX with AWX
  company: Neoflex Consulting
  license: Apache

  min_ansible_version: 2.4
  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: []

dependencies: []
