---
- name: Extract files into "{{ was_tmp_dir }}"
  unarchive:
    src: "{{ lookup('fileglob', './files/{{ item }}*.tar.gz') }}"
    dest: "{{ was_tmp_dir }}/"
    with_items:
      - "{{ was_distrib_name }}"
    
- name: Generate response file
  template:
    src: "dmgr_response.j2"
    dest: "{{ was_tmp_dir }}/{{ dmgr_response_file_name }}"
...